
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 10;
  public static final int STR = 6;
  public static final int OPENCURLYPARENTEHSIS = 29;
  public static final int CONTINUE = 43;
  public static final int OPENROUNDPARENTEHSIS = 23;
  public static final int SEMI = 27;
  public static final int SMALLEQ = 16;
  public static final int INT = 35;
  public static final int MINUS = 8;
  public static final int STATIC = 33;
  public static final int AND = 19;
  public static final int BIGEQ = 14;
  public static final int OR = 20;
  public static final int COMMA = 28;
  public static final int CLASS = 31;
  public static final int NUM = 3;
  public static final int PLUS = 7;
  public static final int MULTIPLY = 9;
  public static final int IF = 39;
  public static final int ASSIGN = 2;
  public static final int THIS = 44;
  public static final int NOTEQCOMP = 22;
  public static final int CLOSESQUAREPARENTHESIS = 26;
  public static final int DOT = 21;
  public static final int ID = 4;
  public static final int BOOLEAN = 36;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int TRUE = 47;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int NEGATION = 11;
  public static final int NULL = 49;
  public static final int OPENSQUAREPARENTEHSIS = 25;
  public static final int BREAK = 42;
  public static final int VOID = 34;
  public static final int EQ = 17;
  public static final int ELSE = 40;
  public static final int WHILE = 41;
  public static final int SMALL = 15;
  public static final int CLOSECURLYPARENTHESIS = 30;
  public static final int CLASS_ID = 5;
  public static final int BIG = 13;
  public static final int CLOSEROUNDPARENTHESIS = 24;
  public static final int EQCOMP = 18;
  public static final int EXTENDS = 32;
  public static final int REMAINDER = 12;
  public static final int STRING = 37;
  public static final int FALSE = 48;
  public static final int LENGTH = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "NUM",
  "ID",
  "CLASS_ID",
  "STR",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "NEGATION",
  "REMAINDER",
  "BIG",
  "BIGEQ",
  "SMALL",
  "SMALLEQ",
  "EQ",
  "EQCOMP",
  "AND",
  "OR",
  "DOT",
  "NOTEQCOMP",
  "OPENROUNDPARENTEHSIS",
  "CLOSEROUNDPARENTHESIS",
  "OPENSQUAREPARENTEHSIS",
  "CLOSESQUAREPARENTHESIS",
  "SEMI",
  "COMMA",
  "OPENCURLYPARENTEHSIS",
  "CLOSECURLYPARENTHESIS",
  "CLASS",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "STRING",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "LENGTH",
  "TRUE",
  "FALSE",
  "NULL"
  };
}

