
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int LCBR = 26;
  public static final int STR = 5;
  public static final int CONTINUE = 40;
  public static final int SEMI = 28;
  public static final int SMALLEQ = 15;
  public static final int INT = 47;
  public static final int MINUS = 7;
  public static final int STATIC = 32;
  public static final int AND = 18;
  public static final int BIGEQ = 13;
  public static final int LP = 22;
  public static final int OR = 19;
  public static final int COMMA = 29;
  public static final int CLASS = 30;
  public static final int RP = 23;
  public static final int NUM = 2;
  public static final int PLUS = 6;
  public static final int MULTIPLY = 8;
  public static final int IF = 36;
  public static final int THIS = 41;
  public static final int NOTEQCOMP = 21;
  public static final int DOT = 20;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int RETURN = 35;
  public static final int RCBR = 27;
  public static final int LB = 24;
  public static final int TRUE = 44;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int NEGATION = 10;
  public static final int RB = 25;
  public static final int NULL = 46;
  public static final int BREAK = 39;
  public static final int VOID = 33;
  public static final int EQ = 16;
  public static final int ELSE = 37;
  public static final int WHILE = 38;
  public static final int SMALL = 14;
  public static final int CLASS_ID = 4;
  public static final int BIG = 12;
  public static final int EQCOMP = 17;
  public static final int EXTENDS = 31;
  public static final int REMAINDER = 11;
  public static final int STRING = 48;
  public static final int FALSE = 45;
  public static final int LENGTH = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "ID",
  "CLASS_ID",
  "STR",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "NEGATION",
  "REMAINDER",
  "BIG",
  "BIGEQ",
  "SMALL",
  "SMALLEQ",
  "EQ",
  "EQCOMP",
  "AND",
  "OR",
  "DOT",
  "NOTEQCOMP",
  "LP",
  "RP",
  "LB",
  "RB",
  "LCBR",
  "RCBR",
  "SEMI",
  "COMMA",
  "CLASS",
  "EXTENDS",
  "STATIC",
  "VOID",
  "BOOLEAN",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "LENGTH",
  "TRUE",
  "FALSE",
  "NULL",
  "INT",
  "STRING"
  };
}

